query HomePage {
  site: _site {
    favicon: faviconMetaTags {
      ...metaTags
    }
  }

  homePage {
    ...HomePageFields
  }

  skills: allSkills {
    __typename
    id
    name
    icon {
      id
      url
      alt
    }
  }

  projects: allProjects {
    ...ProjectFields
  }
}
