query HomePage {
  site: _site {
    favicon: faviconMetaTags {
      ...metaTags
    }
  }

  homePage {
    ...HomePageFields
  }

  skills: allSkills {
    ...SkillFields
  }

  projects: allProjects {
    ...ProjectFields
  }
}
