import type { NextPage } from 'next';
import Head from 'next/head';

import { Layout, Container, Footer } from 'components';

const Home: NextPage = () => {
  return (
    <Layout preview={false}>
      <Head>
        <title>Pukapuka</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <h1 className="title">Welcome to Pukapuka!</h1>

        <p className="description">
          Get started by editing <code className="code">pages/index.tsx</code>
        </p>

        <p className="description">
          If you are seeing this message, you haven&apos;t finished connecting this project to
          DatoCMS and have been redirected to <code className="code">pages/static/index.tsx</code>{' '}
          as a result.
        </p>

        <div className="Grid">
          <a href="https://nextjs.org/docs" className="Grid-cell">
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className="Grid-cell">
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href="https://github.com/vercel/next.js/tree/master/examples" className="Grid-cell">
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="Grid-cell"
          >
            <h2>Deploy &rarr;</h2>
            <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
          </a>
        </div>
      </Container>
      <Footer />
    </Layout>
  );
};

export default Home;
